# Generated by Django 4.2.13 on 2024-06-26 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_candidate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 26, 3, 6, 5, 814162)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
