# Generated by Django 4.2.13 on 2024-06-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_candidate_created_at_candidate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
